// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations; 
using Oryx.Spider.StandardV3.Infrastructures;

namespace Oryx.Spider.StandardV3.Migrations
{
    [DbContext(typeof(SpiderDbContext))]
    [Migration("20181109093643_initcreate")]
    partial class initcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Oryx.Spider.StandardV3.Infrastructures.SpiderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Html");

                    b.Property<int>("Order");

                    b.Property<string>("ParentName");

                    b.Property<string>("ParentUrl");

                    b.Property<bool>("ReloadSuccess");

                    b.Property<string>("TargetUrl");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("SpiderLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
