// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Oryx.Common.Model.SandBox;
using Oryx.CommonDbOperation;
using Oryx.Content.Model;
using Oryx.Social.Model;
using System;

namespace Oryx.Shop.BusinessApi.Migrations
{
    [DbContext(typeof(CommonDbContext))]
    [Migration("20191118120745_updateStoreMapInfo")]
    partial class updateStoreMapInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Oryx.Common.Model.SandBox.SandBoxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AttentionInfo");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("FromUserAccountId");

                    b.Property<bool>("IsRead");

                    b.Property<int>("MessageType");

                    b.Property<string>("RecieveToken");

                    b.Property<long>("TimeStamp");

                    b.Property<Guid>("ToUserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("FromUserAccountId");

                    b.HasIndex("ToUserAccountId");

                    b.ToTable("SandBoxMessage");
                });

            modelBuilder.Entity("Oryx.Common.Model.TipEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Link");

                    b.Property<DateTime?>("PublishTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("TipEntry");
                });

            modelBuilder.Entity("Oryx.Content.Model.Banners", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Link");

                    b.Property<int>("Order");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Oryx.Content.Model.Categories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<int>("Fee");

                    b.Property<bool>("IsShowTop");

                    b.Property<string>("Name");

                    b.Property<Guid?>("ParentCategoryId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Oryx.Content.Model.CategoryComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid?>("ParentCommentId");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("CategoryComment");
                });

            modelBuilder.Entity("Oryx.Content.Model.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<Guid?>("ContentEntryId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid?>("ParentCommentId");

                    b.Property<Guid?>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("ContentEntryId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Oryx.Content.Model.ContentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<int>("Fee");

                    b.Property<bool>("IsFaq");

                    b.Property<bool>("IsTop");

                    b.Property<int>("Order");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ContentEntry");
                });

            modelBuilder.Entity("Oryx.Content.Model.ContentEntryExtension.ContentEntryInfo", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Author");

                    b.Property<string>("Source");

                    b.Property<string>("Type");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("ContentEntryInfo");
                });

            modelBuilder.Entity("Oryx.Content.Model.ContentPayLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CostMoney");

                    b.Property<int>("CostRewardPoints");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("PayContentId");

                    b.Property<int>("PayContentType");

                    b.Property<int>("PayType");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.ToTable("ContentPayLog");
                });

            modelBuilder.Entity("Oryx.Content.Model.ContentUserReadLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<Guid>("ContentEntryId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContentEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("ContentUserReadLog");
                });

            modelBuilder.Entity("Oryx.Content.Model.FileEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActualPath");

                    b.Property<Guid?>("CategoryId");

                    b.Property<Guid?>("ContentEntryId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<string>("Extension");

                    b.Property<string>("Icon");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("PhysicalPath");

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContentEntryId");

                    b.ToTable("FileEntry");
                });

            modelBuilder.Entity("Oryx.Content.Model.SocialExtension.CategoryPostEntryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("PostEntryId");

                    b.HasKey("Id");

                    b.ToTable("CategoryPostEntryMapping");
                });

            modelBuilder.Entity("Oryx.Content.Model.SocialExtension.ContentExtPostEntryTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("LinkId");

                    b.Property<string>("LinkType");

                    b.Property<string>("TopicText");

                    b.HasKey("Id");

                    b.ToTable("ContentExtPostEntryTopic");
                });

            modelBuilder.Entity("Oryx.Content.Model.SocialExtension.ContentPostEntryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ContentId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("PostEntryId");

                    b.HasKey("Id");

                    b.ToTable("ContentPostEntryMapping");
                });

            modelBuilder.Entity("Oryx.Content.Model.Tags", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryId");

                    b.Property<Guid?>("ContentEntryId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContentEntryId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Oryx.DataPlatform.Model.CityInfo", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("ParentCode");

                    b.HasKey("Code");

                    b.ToTable("CityInfos");
                });

            modelBuilder.Entity("Oryx.DataPlatform.Model.StoreMapInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Biz_Cost");

                    b.Property<string>("Biz_Rating");

                    b.Property<string>("City");

                    b.Property<string>("District");

                    b.Property<string>("IdCode");

                    b.Property<string>("Locaiton");

                    b.Property<string>("Name");

                    b.Property<string>("Photos");

                    b.Property<string>("Province");

                    b.Property<string>("Tel");

                    b.Property<string>("Type");

                    b.Property<string>("TypeCode");

                    b.HasKey("Id");

                    b.ToTable("StoreMapInfos");
                });

            modelBuilder.Entity("Oryx.Social.Model.ChatCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ChatLogId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ChatLogId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatCollection");
                });

            modelBuilder.Entity("Oryx.Social.Model.ChatLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.HasKey("Id");

                    b.ToTable("ChatLog");
                });

            modelBuilder.Entity("Oryx.Social.Model.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ChageLogId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("FromUserId");

                    b.Property<bool>("IsReaded");

                    b.Property<string>("MessageContent");

                    b.Property<int>("MsgType");

                    b.Property<long>("TimeStamp");

                    b.Property<Guid>("ToUserId");

                    b.HasKey("Id");

                    b.HasIndex("ChageLogId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsSoftDelete");

                    b.Property<int>("LikeSum");

                    b.Property<int>("Order");

                    b.Property<string>("PostEntryTopic");

                    b.Property<string>("TextContent");

                    b.Property<long>("TimeStamp");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PostEntry");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryCommentLikedLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("PostEntryCommentId");

                    b.Property<Guid>("PostEntryId");

                    b.Property<Guid>("UserAccountEntryId");

                    b.HasKey("Id");

                    b.HasIndex("PostEntryCommentId");

                    b.HasIndex("PostEntryId");

                    b.HasIndex("UserAccountEntryId");

                    b.ToTable("PostEntryCommentLikedLog");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryComments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("LikeNum");

                    b.Property<Guid?>("ParentCommentId");

                    b.Property<Guid?>("PostEntryId");

                    b.Property<long>("TimeStamp");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostEntryId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("PostEntryComments");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActualPath");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<Guid?>("PostEntryId");

                    b.Property<string>("Tag");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PostEntryId");

                    b.ToTable("PostEntryFile");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryLikedLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("PostEntryId");

                    b.Property<Guid>("UserAccountEntryId");

                    b.HasKey("Id");

                    b.HasIndex("PostEntryId");

                    b.HasIndex("UserAccountEntryId");

                    b.ToTable("PostEntryLikedLog");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntrySocialInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LikeNum");

                    b.Property<Guid?>("PostEntryId");

                    b.HasKey("Id");

                    b.HasIndex("PostEntryId");

                    b.ToTable("PostEntrySocialInfo");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PostEntryId");

                    b.HasKey("Id");

                    b.HasIndex("PostEntryId");

                    b.ToTable("PostEntryTags");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("PosterId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("PosterId");

                    b.ToTable("PostEntryTopic");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryUserAnchor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NextTimeStamp");

                    b.Property<int>("NextTimeStampOrder");

                    b.Property<int>("PrevTimeStamp");

                    b.Property<int>("PrevTimeStampOrder");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("PostEntryUserAnchor");
                });

            modelBuilder.Entity("Oryx.Social.Model.UserSocialRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<Guid>("RelationConnectorId");

                    b.Property<Guid>("RelationOnwerId");

                    b.HasKey("Id");

                    b.HasIndex("RelationConnectorId");

                    b.HasIndex("RelationOnwerId");

                    b.ToTable("UserSocialRelationship");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("NickName");

                    b.HasKey("Id");

                    b.ToTable("UserAccountEntry");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserAccountEmail");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountInviteOrign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("InviteKey");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserAccountInviteOrign");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountLoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("IP");

                    b.Property<Guid>("UserAccountEntryId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountEntryId");

                    b.ToTable("UserAccountLoginLogs");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Phone");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserAccountPhone");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDay");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Location");

                    b.Property<string>("TrueName");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserAccountProfile");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountUserNamePwd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Password");

                    b.Property<Guid>("UserAccountId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserAccountUserNamePwd");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountWeChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UnionId");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserAccountWeChat");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.WeChatAccountOpenIdMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OpenId");

                    b.Property<string>("Source");

                    b.Property<string>("Type");

                    b.Property<string>("UnionId");

                    b.Property<Guid?>("UserAccountWechatId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountWechatId");

                    b.ToTable("WeChatAccountOpenIdMapping");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserBusinessExtend.UserAccountBusinessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("RoleName");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("UserAccountBusinessRole");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.Wallet.MoneyWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<decimal>("Money");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("MoneyWallet");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.Wallet.RewardPointWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<decimal>("RewardPoints");

                    b.Property<Guid>("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("RewardPointWallet");
                });

            modelBuilder.Entity("Oryxl.DynamicPage.Model.ReponseEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsMaster");

                    b.Property<Guid?>("MasterId");

                    b.Property<string>("PageBody");

                    b.Property<Guid?>("RouteId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("RouteId")
                        .IsUnique();

                    b.ToTable("ReponseEntry");
                });

            modelBuilder.Entity("Oryxl.DynamicPage.Model.RouteEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<Guid?>("ParentRouteId");

                    b.Property<string>("ParentValue");

                    b.Property<string>("RouteLevel");

                    b.Property<string>("RouteValue");

                    b.Property<string>("TotalRouteValue");

                    b.HasKey("Id");

                    b.HasIndex("ParentRouteId");

                    b.ToTable("RouteEntry");
                });

            modelBuilder.Entity("Oryx.Common.Model.SandBox.SandBoxMessage", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "FromUserAccount")
                        .WithMany()
                        .HasForeignKey("FromUserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "ToUserAccount")
                        .WithMany()
                        .HasForeignKey("ToUserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Content.Model.Categories", b =>
                {
                    b.HasOne("Oryx.Content.Model.Categories", "ParentCategory")
                        .WithMany("ChildrenCategories")
                        .HasForeignKey("ParentCategoryId");
                });

            modelBuilder.Entity("Oryx.Content.Model.CategoryComment", b =>
                {
                    b.HasOne("Oryx.Content.Model.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.Content.Model.CategoryComment", "ParentComment")
                        .WithMany("ChildrenComment")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Content.Model.Comment", b =>
                {
                    b.HasOne("Oryx.Content.Model.ContentEntry", "ContentEntry")
                        .WithMany("Comments")
                        .HasForeignKey("ContentEntryId");

                    b.HasOne("Oryx.Content.Model.Comment", "ParentComment")
                        .WithMany("ChildrenComment")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");
                });

            modelBuilder.Entity("Oryx.Content.Model.ContentEntry", b =>
                {
                    b.HasOne("Oryx.Content.Model.Categories", "Category")
                        .WithMany("ContentList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Content.Model.ContentEntryExtension.ContentEntryInfo", b =>
                {
                    b.HasOne("Oryx.Content.Model.ContentEntry", "ContentEntry")
                        .WithOne("ContentEntryInfo")
                        .HasForeignKey("Oryx.Content.Model.ContentEntryExtension.ContentEntryInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Content.Model.ContentUserReadLog", b =>
                {
                    b.HasOne("Oryx.Content.Model.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.Content.Model.ContentEntry", "ContentEntry")
                        .WithMany()
                        .HasForeignKey("ContentEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Content.Model.FileEntry", b =>
                {
                    b.HasOne("Oryx.Content.Model.Categories", "Categories")
                        .WithMany("MediaResource")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Oryx.Content.Model.ContentEntry", "ContentEntry")
                        .WithMany("MediaResource")
                        .HasForeignKey("ContentEntryId");
                });

            modelBuilder.Entity("Oryx.Content.Model.Tags", b =>
                {
                    b.HasOne("Oryx.Content.Model.Categories", "Categories")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Oryx.Content.Model.ContentEntry", "ContentEntry")
                        .WithMany("Tags")
                        .HasForeignKey("ContentEntryId");
                });

            modelBuilder.Entity("Oryx.Social.Model.ChatCollection", b =>
                {
                    b.HasOne("Oryx.Social.Model.ChatLog", "ChatLog")
                        .WithMany("ChatCollection")
                        .HasForeignKey("ChatLogId");

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccountEntry")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Social.Model.ChatMessage", b =>
                {
                    b.HasOne("Oryx.Social.Model.ChatLog", "ChageLog")
                        .WithMany("ChatMessageList")
                        .HasForeignKey("ChageLogId");

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntry", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccountEntry")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryCommentLikedLog", b =>
                {
                    b.HasOne("Oryx.Social.Model.PostEntryComments", "PostEntryComments")
                        .WithMany()
                        .HasForeignKey("PostEntryCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.Social.Model.PostEntry", "PostEntry")
                        .WithMany()
                        .HasForeignKey("PostEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccountEntry")
                        .WithMany()
                        .HasForeignKey("UserAccountEntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryComments", b =>
                {
                    b.HasOne("Oryx.Social.Model.PostEntryComments", "ParentComment")
                        .WithMany("ChildrenComment")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Oryx.Social.Model.PostEntry", "PostEntry")
                        .WithMany("PostEntryCommentList")
                        .HasForeignKey("PostEntryId");

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryFile", b =>
                {
                    b.HasOne("Oryx.Social.Model.PostEntry")
                        .WithMany("PostEntryFileList")
                        .HasForeignKey("PostEntryId");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryLikedLog", b =>
                {
                    b.HasOne("Oryx.Social.Model.PostEntry", "PostEntry")
                        .WithMany()
                        .HasForeignKey("PostEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccounetEntry")
                        .WithMany()
                        .HasForeignKey("UserAccountEntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntrySocialInfo", b =>
                {
                    b.HasOne("Oryx.Social.Model.PostEntry", "PostEntry")
                        .WithMany()
                        .HasForeignKey("PostEntryId");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryTag", b =>
                {
                    b.HasOne("Oryx.Social.Model.PostEntry")
                        .WithMany("PostEntryTags")
                        .HasForeignKey("PostEntryId");
                });

            modelBuilder.Entity("Oryx.Social.Model.PostEntryTopic", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "PosterAccount")
                        .WithMany()
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.Social.Model.UserSocialRelationship", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "RelationConnectorAccount")
                        .WithMany()
                        .HasForeignKey("RelationConnectorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "RelationOnwerAccount")
                        .WithMany()
                        .HasForeignKey("RelationOnwerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountEmail", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithOne("Email")
                        .HasForeignKey("Oryx.UserAccount.Model.UserAccountExtend.UserAccountEmail", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountInviteOrign", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithOne("InviteOrigin")
                        .HasForeignKey("Oryx.UserAccount.Model.UserAccountExtend.UserAccountInviteOrign", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountLoginLog", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccountEntry")
                        .WithMany()
                        .HasForeignKey("UserAccountEntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountPhone", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithOne("Phone")
                        .HasForeignKey("Oryx.UserAccount.Model.UserAccountExtend.UserAccountPhone", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountProfile", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithOne("Profile")
                        .HasForeignKey("Oryx.UserAccount.Model.UserAccountExtend.UserAccountProfile", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountUserNamePwd", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithOne("UserNamePwd")
                        .HasForeignKey("Oryx.UserAccount.Model.UserAccountExtend.UserAccountUserNamePwd", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.UserAccountWeChat", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithOne("WeChat")
                        .HasForeignKey("Oryx.UserAccount.Model.UserAccountExtend.UserAccountWeChat", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserAccountExtend.WeChatAccountOpenIdMapping", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountExtend.UserAccountWeChat", "UserAccountWechat")
                        .WithMany("OpenIdMapping")
                        .HasForeignKey("UserAccountWechatId");
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.UserBusinessExtend.UserAccountBusinessRole", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "UserAccount")
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.Wallet.MoneyWallet", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "Account")
                        .WithOne("MoneyWallet")
                        .HasForeignKey("Oryx.UserAccount.Model.Wallet.MoneyWallet", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryx.UserAccount.Model.Wallet.RewardPointWallet", b =>
                {
                    b.HasOne("Oryx.UserAccount.Model.UserAccountEntry", "Account")
                        .WithOne("RewardPointWallet")
                        .HasForeignKey("Oryx.UserAccount.Model.Wallet.RewardPointWallet", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oryxl.DynamicPage.Model.ReponseEntry", b =>
                {
                    b.HasOne("Oryxl.DynamicPage.Model.ReponseEntry", "Master")
                        .WithMany()
                        .HasForeignKey("MasterId");

                    b.HasOne("Oryxl.DynamicPage.Model.RouteEntry", "Route")
                        .WithOne("Page")
                        .HasForeignKey("Oryxl.DynamicPage.Model.ReponseEntry", "RouteId");
                });

            modelBuilder.Entity("Oryxl.DynamicPage.Model.RouteEntry", b =>
                {
                    b.HasOne("Oryxl.DynamicPage.Model.RouteEntry", "ParentRoute")
                        .WithMany("Children")
                        .HasForeignKey("ParentRouteId");
                });
#pragma warning restore 612, 618
        }
    }
}
